# Machine Learning Tutorial Python - 3: Linear Regression With Multiple Variables a.k.a 

## Multivariate Regression

In this machine learning tutorial with python, we will write python code to predict home prices using multivariate linear regression in python (using sklearn linear_model). Home prices are dependent on 3 independent variables: area, bedrooms and age. Pandas dataframe is used to fill missing values first and then use that dataset to train a multivariate regression model.You can use exercise at the end to consolidate your understanding on whatever you have learnt in this machine learning tutorial.

Code: https://github.com/codebasics/py/blob...
(Exercise is at the end of the ipynb notebook so just open that file and read through)

Exercise solution: https://github.com/codebasics/py/blob...

Given the home prices find out the price of a home that has,
1. 3000 sqr ft area, 3 bedrooms, and 40 years old
2. 2500 sqr ft area, 4 bedrooms, and 5 years old

Credit: https://www.youtube.com/watch?v=J_LnPL3Qg70&list=PLeo1K3hjS3uvCeTYTeyfe0-rN5r8zn9rw&index=3
#### Owner: codebasics

## Topics
1. Data Preprocessing: Handling NA values
2. Liner Regression using multiple variables

In [2]:
import pandas as pd
import numpy as np
#import matplotlib.pyplot as plt
from sklearn import linear_model

In [3]:
df = pd.read_csv("homeprices.csv")
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       NaN   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

#### Data Preprocessing: Fill NA values with median value of a column

In [4]:
df.bedrooms.median()

4.0

In [5]:
import math
median_bedrooms = math.floor(df.bedrooms.median())
median_bedrooms

4

In [6]:
df.bedrooms.fillna(median_bedrooms) #pandas series menthod
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       NaN   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

In [7]:
df.bedrooms = df.bedrooms.fillna(median_bedrooms)
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       4.0   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

### linear regression model with multiple features or independent variables and as usual single dependent variable
Here <b>area, bedrooms, age</b> are called <b>independant variables or features</b> whereas <b>price is a dependant variable</b>

In [10]:
reg = linear_model.LinearRegression()
# include independant variables and dependant variable
reg.fit(df[['area','bedrooms','age']],df.price) 

# exclude dependant variables and dependant variable
#reg.fit(df.drop('price',axis='columns'),df.price) # this one and above line of code, both is same

LinearRegression()

In [12]:
reg.coef_

array([  112.06244194, 23388.88007794, -3231.71790863])

In [13]:
reg.intercept_

221323.00186540443

#### Find price of home with 3000 sqr ft area, 3 bedrooms, 40 year old

In [14]:
reg.predict([[3000,3,40]])

C:\Users\39762\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([498408.25158031])

In [12]:
(137.25 * 3000) + (-26025 * 3) + (-6825 * 40) + 383724.99999999994

444399.99999999994

#### Find price of home with 2500 sqr ft area, 4 bedrooms, 5 year old

In [16]:
reg.predict([[2500,4,5]])

C:\Users\39762\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([578876.03748933])

## Exercise
In exercise folder (same level as this notebook on github) there is hiring.csv. This file contains hiring statics for a firm such as experience of candidate, his written test score and personal interview score. Based on these 3 factors, HR will decide the salary. Given this data, you need to build a machine learning model for HR department that can help them decide salaries for future candidates. Using this predict salaries for following candidates,

2 yr experience, 9 test score, 6 interview score

12 yr experience, 10 test score, 10 interview score

#### Answer
53713.86 and 93747.79